#!/usr/bin/env bash
# Rebuild the generated indexes from the ticket files.
#
#   backlog/index.sh            rewrite OPEN.md and DONE.md
#   backlog/index.sh --stdout   print both, write nothing
#   backlog/index.sh --check    exit 1 if either is out of date
#
# The script owns every generated file whole. Edits by hand are lost on the
# next run.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

collect() {
  local files=()
  local d
  for d in todo doing parked; do
    while IFS= read -r -d '' f; do files+=("$f"); done \
      < <(find "$ROOT/$d" -maxdepth 1 -name '*.md' -print0 2>/dev/null | sort -z)
  done
  while IFS= read -r -d '' f; do files+=("$f"); done \
    < <(find "$ROOT/done" -mindepth 2 -maxdepth 2 -name '*.md' -print0 2>/dev/null | sort -z)

  [ ${#files[@]} -eq 0 ] && return 0

  awk -v root="$ROOT" '
    function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }
    function clean(s) { sub(/[ \t]+#.*$/, "", s); return trim(s) }
    function unquote(s) {
      if (s ~ /^".*"$/ || s ~ /^'"'"'.*'"'"'$/) s = substr(s, 2, length(s) - 2)
      return s
    }
    function emit(   kind, key, rank, sid) {
      if (path == "") return
      rank = (pri == "p0") ? 0 : (pri == "p1") ? 1 : (pri == "p2") ? 2 : (pri == "p3") ? 3 : 8
      # Ids keep their US-/BUG- prefix (see README): sort on the digits, and
      # offset bugs so US-019 and BUG-019 cannot tie.
      num = match(id, /[0-9]+$/) ? substr(id, RSTART) + 0 : 999999
      if (id ~ /^BUG-/) num += 1000
      sid = sprintf("%06d", num)
      if (status == "done") {
        kind = "done"
        key = month "|" sid
      } else {
        kind = "open"
        key = rank "|" ((status == "doing") ? 0 : (status == "todo") ? 1 : 2) "|" sid
      }
      printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
        kind, key, id, title, type, pri, status, created, resolution, path, area
    }
    FNR == 1 {
      emit()
      id = title = type = pri = status = created = resolution = month = area = ""
      path = FILENAME; sub(root "/", "", path)
      n = split(path, part, "/")
      if (n >= 3 && part[1] == "done") { status = "done"; month = part[2] }
      else { status = part[1] }
      fm = ($0 == "---") ? 1 : 0
      next
    }
    !fm { next }
    $0 == "---" { fm = 0; next }
    {
      p = index($0, ":")
      if (p == 0) next
      k = trim(substr($0, 1, p - 1))
      v = substr($0, p + 1)
      if (k == "id")              id = clean(v)
      else if (k == "title")      title = unquote(trim(v))
      else if (k == "type")       type = clean(v)
      else if (k == "priority")   pri = clean(v)
      else if (k == "created")    created = clean(v)
      else if (k == "area")       area = clean(v)
      else if (k == "resolution") resolution = clean(v)
    }
    END { emit() }
  ' "${files[@]}"
}

# render <open|done> — print the whole file for that table.
render() {
  awk -F'\t' -v rows="$(collect)" -v want="$1" '
    function cell(s) { gsub(/\|/, "\\|", s); return (s == "") ? "—" : s }
    function sortish(a, len,   i, j, t, tf, jf) {
      for (i = 2; i <= len; i++) {
        t = a[i]; split(t, tf, "\t")
        for (j = i - 1; j >= 1; j--) {
          split(a[j], jf, "\t")
          if (jf[2] <= tf[2]) break
          a[j + 1] = a[j]
        }
        a[j + 1] = t
      }
    }
    BEGIN {
      n = split(rows, line, "\n")
      for (i = 1; i <= n; i++) {
        if (line[i] == "") continue
        split(line[i], f, "\t")
        if (f[1] != want) continue
        row[++c] = line[i]
        by_status[f[7]]++
        by_pri[f[6] == "" ? "—" : f[6]]++
      }
      sortish(row, c)

      print "<!-- Generated by backlog/index.sh. Do not edit by hand. -->"
      print ""

      if (want == "open") {
        print "# Open tickets"
        print ""
        if (c == 0) {
          print "_Nothing open._"
        } else {
          printf "%d open — %d doing, %d todo, %d parked", \
            c, by_status["doing"] + 0, by_status["todo"] + 0, by_status["parked"] + 0
          s = ""
          split("p0 p1 p2 p3", order, " ")
          for (i = 1; i <= 4; i++)
            if (by_pri[order[i]] > 0) s = s (s == "" ? "" : ", ") by_pri[order[i]] " " order[i]
          if (s != "") printf " (%s)", s
          print "."
          print ""
          print "| Priority | ID | Ticket | Type | Status | Created |"
          print "| --- | ---: | --- | --- | --- | --- |"
          for (i = 1; i <= c; i++) {
            split(row[i], f, "\t")
            printf "| %s | %s | [%s](%s) | %s | %s | %s |\n", \
              cell(f[6]), cell(f[3]), cell(f[4]), f[10], cell(f[5]), cell(f[7]), cell(f[8])
          }
        }
        print ""
        print "Finished work is in [DONE.md](DONE.md). The rules and the ticket"
        print "format are in [README.md](README.md)."
      } else {
        print "# Done"
        print ""
        if (c == 0) {
          print "_Nothing finished yet._"
        } else {
          printf "%d finished.\n", c
          print ""
          print "| ID | Ticket | Type | Resolution | Month |"
          print "| ---: | --- | --- | --- | --- |"
          for (i = c; i >= 1; i--) {
            split(row[i], f, "\t")
            m = f[10]; sub(/^done\//, "", m); sub(/\/.*$/, "", m)
            printf "| %s | [%s](%s) | %s | %s | %s |\n", \
              cell(f[3]), cell(f[4]), f[10], cell(f[5]), cell(f[9]), cell(m)
          }
        }
        print ""
        print "Open work is in [OPEN.md](OPEN.md). The rules and the ticket"
        print "format are in [README.md](README.md)."
      }
    }
  '
}

case "${1-}" in
  --stdout)
    for k in open done; do
      printf '==> %s <==\n' "$([ "$k" = open ] && echo OPEN.md || echo DONE.md)"
      render "$k"
      echo
    done
    ;;
  --check)
    stale=0
    for k in open done; do
      f="$ROOT/$([ "$k" = open ] && echo OPEN.md || echo DONE.md)"
      if ! diff -q <(render "$k") "$f" >/dev/null 2>&1; then
        echo "stale: ${f#"$ROOT/"}" >&2
        stale=1
      fi
    done
    if [ "$stale" = 1 ]; then
      echo "run backlog/index.sh" >&2
      exit 1
    fi
    echo "OPEN.md and DONE.md are up to date"
    ;;
  "")
    for k in open done; do
      f="$ROOT/$([ "$k" = open ] && echo OPEN.md || echo DONE.md)"
      tmp="$(mktemp)"
      render "$k" > "$tmp"
      mv "$tmp" "$f"
      chmod 644 "$f"
      echo "updated ${f#"$ROOT/"}"
    done
    ;;
  *) echo "usage: index.sh [--stdout|--check]" >&2; exit 2 ;;
esac
