/**
 * The tables this application owns. US-153.
 *
 * The pipeline knows an account as a text id and no more: every table it owns
 * carries `user_id text` with no foreign key here, and it never joins these.
 * What an account *is* — a login, a session, a subscription, a finished
 * setup — is this application's to decide, and the private cloud repository
 * decides it differently. These six tables are the whole of that decision
 * today.
 *
 * They are applied by their own migration stream, `apps/api/drizzle`, under
 * their own migrations table, beside the pipeline's. `db/migrate.ts` runs the
 * pipeline's first. A database older than the split already has these tables
 * from the pipeline's history, which is why the first migration here creates
 * nothing that exists.
 */
import { sql } from "drizzle-orm";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { boolean, check, pgTable, text, timestamp } from "drizzle-orm/pg-core";

/**
 * The four tables Better Auth owns. US-017.
 *
 * Better Auth addresses a Drizzle schema by the key a table is exported under
 * and each column by its **property name**, so every property here is the
 * camel-case field name the library asks for. The SQL column beside it is
 * snake case, which is this schema's own convention, and the two are free to
 * differ. Change a property name and the library stops finding the column,
 * with no type error to say so.
 *
 * They are declared here rather than generated by Better Auth's CLI, because
 * this repository has one migration path and `drizzle-kit` reads one schema
 * file. A second tool writing tables into the same database would take the
 * "one migration number, one file" rule away.
 *
 * Nothing outside `auth/` reads these. The rest of the application knows a
 * user as a text id and no more, which is what makes `singleUserId` a value
 * this replaces rather than a shape it changes.
 */
export const users = pgTable("users", {
  /** Better Auth generates it, so text and not `uuid`. */
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * One row per signed-in browser.
 *
 * `expiresAt` is the server's copy of the deadline and it is the one that
 * counts. A cookie carries its own expiry, and a cookie is a thing the browser
 * holds — the row here is what makes signing out and expiry real rather than
 * advisory. US-017's acceptance asks for exactly that.
 *
 * `on delete cascade`: deleting a person deletes their sessions in the same
 * statement, so no session can outlive the account it belongs to.
 */
export const sessions = pgTable("sessions", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
});

/**
 * How a person proves who they are. One row per method.
 *
 * Email and password is the only method US-017 ships, and for it `password`
 * holds Better Auth's hash — never a password, and never anything this
 * application writes or reads. The OAuth columns are unused and are here
 * because the library writes them the day somebody enables a social provider,
 * and a missing column is a runtime failure rather than a type error.
 */
export const accounts = pgTable("accounts", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
  scope: text("scope"),
  /** Better Auth's hash of the password. Nothing here ever reads it. */
  password: text("password"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Short-lived tokens Better Auth issues, such as a password reset. */
export const verifications = pgTable("verifications", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * What a subscription can be. US-072.
 *
 * Five values and no more, because every one of them has to answer one
 * question: may this account write and may its monitors poll? Stripe's own
 * status set is larger — `incomplete_expired`, `unpaid`, `paused` — and each
 * of those maps onto one of these rather than being carried through. A status
 * this application does not understand must not reach a table that decides
 * whether somebody is entitled.
 *
 * `trialing` is ours before it is Stripe's. It is written at sign-up with no
 * card and no Stripe object, so for most of its life the row here is the only
 * record of it. See `billing/entitlement.ts`.
 *
 * `past_due` is entitled and `canceled` is not, and that is the one judgement
 * in the list: a card that failed on Tuesday is a person Stripe is still
 * retrying, and turning their monitors off before the retries finish loses
 * data they paid for.
 *
 * There is no `trial_expired`, deliberately. An expired trial is `trialing`
 * with a deadline in the past, which is a fact the clock already holds — a
 * status meaning the same thing would need a job to write it, and until that
 * job ran the row and the clock would disagree about whether somebody may
 * poll.
 */
export const subscriptionStatuses = [
  "trialing",
  "active",
  "past_due",
  "canceled",
  "incomplete",
] as const;
export type SubscriptionStatus = (typeof subscriptionStatuses)[number];

/**
 * One row per account, in a deployment that charges. US-072.
 *
 * No row is a normal state and it means two different things depending on the
 * deployment. Self-hosted, it means billing is off and nobody ever writes
 * here. Hosted, it means an account that predates this table — the owner's own
 * — and `entitlementFor` reads that as entitled rather than as expired,
 * because refusing the first account on the instance that runs the product is
 * not a state anybody should be able to reach through a migration.
 *
 * The Stripe columns are null until somebody opens Checkout. A trial costs
 * nothing, asks for no card, and creates no customer: there is nothing for a
 * payment provider to hold. `stripe_customer_id` is unique so two accounts can
 * never point at one customer, which is how a refund or a cancellation would
 * silently move between people.
 *
 * `current_period_end` is Stripe's number, copied here, and it is not what
 * decides entitlement — `status` is. It exists so a screen can say when the
 * next charge falls without a round trip to Stripe on every page load.
 */
export const subscriptions = pgTable(
  "subscriptions",
  {
    /** The account. One row each, so the account id is the key. */
    userId: text("user_id")
      .primaryKey()
      .references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
    status: text("status").notNull(),
    /**
     * When the seven days run out.
     *
     * Written once, at sign-up, and never moved. A trial that is extended by
     * anything other than a person deliberately extending it is a trial that
     * does not end.
     */
    trialEndsAt: timestamp("trial_ends_at", { withTimezone: true }),
    stripeCustomerId: text("stripe_customer_id").unique(),
    stripeSubscriptionId: text("stripe_subscription_id").unique(),
    /** Stripe's copy of when this period ends. Shown, never used to decide. */
    currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),
    /** Set when somebody cancels and the period has not run out yet. */
    cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    /**
     * The status is checked in the database and not only in TypeScript.
     *
     * This repository has shipped the other way twice — `apify` in US-057 and
     * `draft_reply` in US-040 — and both times a full suite passed and a live
     * run found it after the money was spent. A value added to the array above
     * is not a value the database accepts.
     */
    check(
      "subscriptions_status_known",
      sql`${table.status} in ('trialing', 'active', 'past_due', 'canceled', 'incomplete')`,
    ),
    /**
     * A trial with no deadline is not a trial. Every other status may have
     * none, because a paid subscription's clock is Stripe's.
     */
    check(
      "subscriptions_trial_has_an_end",
      sql`${table.status} <> 'trialing' or ${table.trialEndsAt} is not null`,
    ),
  ],
);

/**
 * One account has finished setting up. US-105.
 *
 * **A row is the fact, and its absence is the only new account there is.** The
 * setup gate in `App.tsx` shows itself only when this row is missing *and* a
 * key is missing, so an account that removes its last key is let in rather
 * than asked to set up again. US-088 derived setup from the keys alone and
 * rejected a flag; this is that decision reversed, on the owner's request. The
 * reasoning is in the ticket.
 *
 * **Written once and never deleted.** Deleting a key must not delete the row,
 * or the gate returns — which is the bug this table exists to fix. The write
 * is `markOnboardingComplete`, an idempotent insert, and the read is
 * `hasCompletedOnboarding`.
 *
 * A text id and no foreign key, for `monitors.user_id`'s reason: a test and a
 * pre-login instance both name an owner the `users` table has never held, and
 * the marker is written by that owner's own setup. Deleting an account leaves
 * the row, which is harmless — the id is never reused.
 */
export const userOnboarding = pgTable("user_onboarding", {
  /** One per account, so the account is the key. */
  userId: text("user_id").primaryKey(),
  completedAt: timestamp("completed_at", { withTimezone: true }).notNull().defaultNow(),
});
