/**
 * The tables this application owns. US-153.
 *
 * The pipeline knows an account as a text id and no more: every table it owns
 * carries `user_id text` with no foreign key here, and it never joins these.
 * What an account *is* — a login, a session, a finished setup — is this
 * application's to decide, and the private cloud repository decides it
 * differently: it charges, and its subscriptions table lives there. These
 * five tables are the whole of that decision here.
 *
 * They are applied by their own migration stream, `apps/api/drizzle`, under
 * their own migrations table, beside the pipeline's. `db/migrate.ts` runs the
 * pipeline's first. A database older than the split already has these tables
 * from the pipeline's history, which is why the first migration here creates
 * nothing that exists.
 */
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { boolean, pgTable, text, timestamp } from "drizzle-orm/pg-core";

/**
 * The four tables Better Auth owns. US-017.
 *
 * Better Auth addresses a Drizzle schema by the key a table is exported under
 * and each column by its **property name**, so every property here is the
 * camel-case field name the library asks for. The SQL column beside it is
 * snake case, which is this schema's own convention, and the two are free to
 * differ. Change a property name and the library stops finding the column,
 * with no type error to say so.
 *
 * They are declared here rather than generated by Better Auth's CLI, because
 * this repository has one migration path and `drizzle-kit` reads one schema
 * file. A second tool writing tables into the same database would take the
 * "one migration number, one file" rule away.
 *
 * Nothing outside `auth/` reads these. The rest of the application knows a
 * user as a text id and no more, which is what makes `singleUserId` a value
 * this replaces rather than a shape it changes.
 */
export const users = pgTable("users", {
  /** Better Auth generates it, so text and not `uuid`. */
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * One row per signed-in browser.
 *
 * `expiresAt` is the server's copy of the deadline and it is the one that
 * counts. A cookie carries its own expiry, and a cookie is a thing the browser
 * holds — the row here is what makes signing out and expiry real rather than
 * advisory. US-017's acceptance asks for exactly that.
 *
 * `on delete cascade`: deleting a person deletes their sessions in the same
 * statement, so no session can outlive the account it belongs to.
 */
export const sessions = pgTable("sessions", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
});

/**
 * How a person proves who they are. One row per method.
 *
 * Email and password is the only method US-017 ships, and for it `password`
 * holds Better Auth's hash — never a password, and never anything this
 * application writes or reads. The OAuth columns are unused and are here
 * because the library writes them the day somebody enables a social provider,
 * and a missing column is a runtime failure rather than a type error.
 */
export const accounts = pgTable("accounts", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
  scope: text("scope"),
  /** Better Auth's hash of the password. Nothing here ever reads it. */
  password: text("password"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Short-lived tokens Better Auth issues, such as a password reset. */
export const verifications = pgTable("verifications", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * One account has finished setting up. US-105.
 *
 * **A row is the fact, and its absence is the only new account there is.** The
 * setup gate in `App.tsx` shows itself only when this row is missing *and* a
 * key is missing, so an account that removes its last key is let in rather
 * than asked to set up again. US-088 derived setup from the keys alone and
 * rejected a flag; this is that decision reversed, on the owner's request. The
 * reasoning is in the ticket.
 *
 * **Written once and never deleted.** Deleting a key must not delete the row,
 * or the gate returns — which is the bug this table exists to fix. The write
 * is `markOnboardingComplete`, an idempotent insert, and the read is
 * `hasCompletedOnboarding`.
 *
 * A text id and no foreign key, for `monitors.user_id`'s reason: a test and a
 * pre-login instance both name an owner the `users` table has never held, and
 * the marker is written by that owner's own setup. Deleting an account leaves
 * the row, which is harmless — the id is never reused.
 */
export const userOnboarding = pgTable("user_onboarding", {
  /** One per account, so the account is the key. */
  userId: text("user_id").primaryKey(),
  completedAt: timestamp("completed_at", { withTimezone: true }).notNull().defaultNow(),
});
