export {
  generateStructured,
  type ModelCall,
  type StructuredCallOptions,
  type StructuredResult,
} from "./ai/call.js";
export {
  type Classification,
  classificationSchema,
  leadScore,
  maximumReasons,
  minimumReasons,
  restatesTheScores,
  scoreColumns,
  scoreWeights,
} from "./ai/classification.js";
export {
  type ClassificationOutcome,
  type Classifier,
  type ClassifierOptions,
  type ClassifyRequest,
  createClassifier,
} from "./ai/classify.js";
export {
  type AiConfig,
  type AiEnvironment,
  type AiProvider,
  aiConfigFromEnvironment,
  aiProviders,
  canEmbed,
  defaultEmbeddingModels,
  draftConfigFromEnvironment,
  type EmbeddingConfig,
  type EmbeddingProvider,
  embeddingConfigFromEnvironment,
  embeddingNeedsApiKey,
  embeddingProviders,
  needsApiKey,
  triageConfigFromEnvironment,
} from "./ai/config.js";
export {
  createProjectDescriber,
  type DescribeResult,
  describeProject,
  maximumDocumentCharacters,
  type ProjectDescriber,
  type ProjectDraft,
} from "./ai/describe.js";
export { createDrafter, type Drafter, type DraftOutcome, type DraftRequest } from "./ai/draft.js";
export { type DraftContext, draftContext } from "./ai/draft-context.js";
export {
  createEmbedder,
  createEmbeddingModel,
  type Embedder,
  type EmbedderOptions,
  type EmbedOutcome,
  estimateEmbeddingCostMicros,
  MissingEmbeddingKeyError,
} from "./ai/embed.js";
export {
  type AiKey,
  aiKeyRecordName,
  type CreateAiKeyInput,
  createAiKey,
  DuplicateAiKeyName,
  deleteAiKey,
  listAiKeys,
  readAiKey,
  readAiKeySecret,
  setDefaultAiKey,
} from "./ai/keys.js";
export {
  type ModelProbe,
  type ModelProbeStatus,
  probeChatModel,
  probeEmbeddingModel,
} from "./ai/probe.js";
export {
  buildSystemPrompt,
  buildUserPrompt,
  type MonitorProfile,
  type PostForClassification,
} from "./ai/prompt.js";
export {
  createModel,
  estimateCostMicros,
  MissingAiKeyError,
  modelPrices,
  pricedModelsFor,
} from "./ai/provider.js";
export {
  buildQuerySystemPrompt,
  buildQueryUserPrompt,
  createQueryGenerator,
  maximumQueries,
  maximumSubreddits,
  minimumQueries,
  type QueryGenerator,
  type QueryGeneratorOptions,
  type QueryPlan,
  type QueryPlanOutcome,
  queryListSchemaFor,
  queryPlanSchemaFor,
  searchQuerySchema,
  searchQuerySchemaFor,
  subredditSchema,
} from "./ai/queries.js";
export {
  followsDefault,
  recommendationsFor,
  recommendedModelFor,
  recommendedProviders,
} from "./ai/recommended.js";
export {
  classifiedPostCounts,
  type RecordModelCallInput,
  recordModelCall,
} from "./ai/record.js";
export {
  buildReplySystemPrompt,
  buildReplyUserPrompt,
  type Draft,
  draftSchema,
  type ReplyVoice,
} from "./ai/reply.js";
export {
  type CreateReplyPromptInput,
  createReplyPrompt,
  DuplicateReplyPromptName,
  deleteReplyPrompt,
  listReplyPrompts,
  type ReplyPrompt,
  seedPresetReplyVoices,
  type UpdateReplyPromptInput,
  updateReplyPrompt,
} from "./ai/reply-prompts.js";
export { type ReplyVoicePreset, replyVoicePresets } from "./ai/reply-voices.js";
export {
  type AiTaskDraft,
  type AiTaskSettings,
  clearAiTaskSettings,
  previewAiEnvironment,
  readAiEnvironment,
  readAiSettings,
  type SaveAiTaskInput,
  saveAiTaskSettings,
} from "./ai/settings.js";
export {
  type Auth,
  accountExists,
  type CreateAuthOptions,
  claimUnownedRows,
  createAuth,
  isOnlyAccount,
  minimumPasswordLength,
  sessionMaxAgeSeconds,
  sessionRefreshAfterSeconds,
} from "./auth/auth.js";
export {
  hasCompletedOnboarding,
  markOnboardingComplete,
} from "./auth/onboarding.js";
export {
  ownerUserId,
  type SignupMode,
  signupModes,
  unclaimedUserId,
} from "./auth/user.js";
export {
  type EmailVerificationEnvironment,
  type EmailVerificationMode,
  emailVerificationModes,
  emailVerificationRequired,
  requiredVerificationVariables,
} from "./auth/verification.js";
export { type SendEmail, verificationMessage } from "./auth/verification-email.js";
export {
  applyStripeSubscription,
  type BillingEnvironment,
  type BillingEvent,
  type BillingMode,
  type BillingProvider,
  type BillingSettings,
  billingModes,
  billingSettingsFrom,
  type CheckoutRequest,
  type CheckoutResult,
  createStripeBilling,
  daysUntil,
  type Entitlement,
  type EntitlementReason,
  entitledCondition,
  entitlementFor,
  type HostedPage,
  handledEventTypes,
  linkStripeCustomer,
  type PlanPrice,
  type PortalRequest,
  readEntitlement,
  readSubscription,
  requiredBillingVariables,
  type StripeSubscriptionState,
  type SubscriptionRecord,
  startTrial,
  stateFromSubscription,
  statusFromStripe,
  subscriptionByCustomer,
  trialDays,
} from "./billing/index.js";
export {
  type BudgetState,
  budgetState,
  budgetStates,
  checkBudget,
  clearBudget,
  createSpendMeter,
  enforceBudget,
  formatMicros,
  getBudget,
  type LastCollection,
  lastCollections,
  type MonitorBudget,
  type MonitorSpend,
  monitorSpend,
  monthStart,
  type PairSpend,
  type RecordSourceUsageInput,
  recordSourceUsage,
  setBudget,
  spendByMonitor,
  spendByPair,
} from "./budget/index.js";
export {
  aiEnvSchema,
  type Env,
  envSchema,
  loadAiEnv,
  loadEnv,
  loadNotificationEnv,
  loadSignupEnv,
  type NotificationEnv,
} from "./config/env.js";
export {
  machineKeysUsable,
  providerKeyEnvironment,
  webhookSecretEnvironment,
  withoutMachineModelKeys,
} from "./config/machine-keys.js";
export { createDatabase, type Database } from "./db/client.js";
export { migrationsFolder, runMigrations } from "./db/migrate.js";
export {
  type AiTask,
  accounts,
  aiKeys,
  aiSettings,
  aiTasks,
  apiUsage,
  budgets,
  defaultMinimumScore,
  defaultPollIntervalSeconds,
  defaultSimilarityThreshold,
  type EstimateProbeKind,
  type EstimateStatus,
  type ExhaustedBehaviour,
  embeddingDimensions,
  estimateProbeKinds,
  estimateStatuses,
  exhaustedBehaviours,
  type FilterStage,
  feedback,
  filterDrops,
  filterStages,
  type IntentType,
  intentTypes,
  type ModelCallOutcome,
  type ModelCallPurpose,
  matches,
  maxResumeAttempts,
  minimumPollIntervalSeconds,
  modelCallOutcomes,
  modelCallPurposes,
  modelCalls,
  monitors,
  type PollOutcome,
  type PollRunSource,
  type PollStopReason,
  type Provider,
  pollOutcomes,
  pollStopReasons,
  posts,
  projects,
  providers,
  queryEstimateProbes,
  queryEstimates,
  replyPrompts,
  type Signal,
  type Source,
  type SubscriptionStatus,
  sessions,
  signals,
  sourceContinuations,
  sourceCredentials,
  sourceProviders,
  sources,
  subscriptionStatuses,
  subscriptions,
  users,
  type Verdict,
  verdicts,
  verifications,
} from "./db/schema.js";
export {
  daysPerMonth,
  type EstimateProbe,
  type EstimateReport,
  type EstimateRun,
  type EstimateSample,
  type EstimateTotals,
  exceedsCap,
  finishEstimate,
  maxEstimateAttempts,
  type PollShape,
  type ProbeProgress,
  type ProbeReport,
  type ProbeRequest,
  type Projection,
  postsPerDay,
  probesFor,
  projectMonthly,
  readEstimate,
  recordProbeProgress,
  refuseEstimate,
  reportFor,
  type StartEstimateInput,
  sampleExcerptLength,
  samplePostsPerProbe,
  samplesKept,
  sampleWindowDays,
  shortestObservedSpanHours,
  startEstimate,
  totalsFor,
} from "./estimate/index.js";
export {
  currentVerdicts,
  type ExportedVerdict,
  exportFeedback,
  noVerdicts,
  type RecordedVerdict,
  type RecordVerdictInput,
  recordVerdict,
  type VerdictCounts,
  verdictCounts,
} from "./feedback/feedback.js";
export {
  type EmbeddablePost,
  type MonitorDescription,
  monitorDescriptionText,
  postEmbeddingText,
} from "./filter/description.js";
export {
  embeddingDropSimilarities,
  type FilterDrop,
  type FilterDropCounts,
  filterDropCounts,
  noFilterDrops,
  recordFilterDrops,
} from "./filter/drops.js";
export {
  type FilterablePost,
  type KeywordRule,
  keepsPost,
  keywordRuleFor,
  ruleIsEmpty,
} from "./filter/keywords.js";
export { createLogger, type Logger, type LoggerOptions, redactedFields } from "./logger.js";
export {
  csvCell,
  csvFilename,
  cursorFor,
  cursorPattern,
  defaultPageSize,
  type InboxMatch,
  type ListMatchesOptions,
  listMatches,
  type MatchPage,
  matchesToCsv,
  matchOwner,
  maximumPageSize,
  rankDecayPointsPerDay,
  setMatchSaved,
  UnusableCursorError,
  utf8ByteOrderMark,
} from "./matches/index.js";
export {
  allMonitorQueries,
  type CreatedMonitor,
  type CreateMonitorInput,
  canFetchRepliesFor,
  createMonitor,
  deleteMonitor,
  describeMissingCredentials,
  describeSignals,
  getMonitor,
  intentTypeLabel,
  latestPollRuns,
  listMonitors,
  type Monitor,
  type MonitorAnswers,
  type MonitorEnvironment,
  type MonitorFilterSettings,
  type MonitorPlan,
  maxPollRunsRead,
  monitorQueries,
  monitorQueryPlan,
  type PollRun,
  type PollRunRecord,
  pauseMonitor,
  pollRunsKeptPerMonitor,
  type ResumeResult,
  readPollRuns,
  recordPollRun,
  redefinesTheMonitor,
  resumeMonitor,
  type SignalDescription,
  signalDescriptions,
  signalList,
  startBlockers,
  type UpdateMonitorInput,
  updateMonitor,
} from "./monitors/index.js";
export { configureNetworking, connectAttemptTimeoutMs } from "./net.js";
export {
  assertPublicHost,
  isPublicAddress,
  PrivateAddressError,
  type ResolveHost,
} from "./notifications/address-guard.js";
export { type NotificationTransport, processNotifications } from "./notifications/deliver.js";
export {
  deleteAccountWebhookSecret,
  generateAccountWebhookSecret,
  generateWebhookSecret,
  readWebhookSecretHint,
  type WebhookSecretHint,
  webhookSecretFor,
  webhookSecretRecordName,
} from "./notifications/secret.js";
export {
  defaultNotificationSettings,
  type NotificationInput,
  notificationDefaults,
  notificationInputSchema,
  notificationIssues,
  readNotificationSettings,
  saveNotificationSettings,
} from "./notifications/settings.js";
export { createNotificationTransport, notificationReadiness } from "./notifications/transport.js";
export {
  acceptedTextTypes,
  type DocumentFailure,
  type DocumentResult,
  fetchDocument,
  isPrivateAddress,
  maximumDocumentBytes,
  readUploadedDocument,
} from "./projects/document.js";
export {
  type CreateProjectInput,
  createProject,
  deleteProject,
  getProject,
  listProjects,
  type Project,
  type ProjectAnswers,
  type UpdateProjectInput,
  updateProject,
} from "./projects/projects.js";
export {
  decryptSecret,
  type EncryptionKey,
  encryptionKeyIsWellFormed,
  encryptSecret,
  generateEncryptionKey,
  InvalidEncryptionKeyError,
  MissingEncryptionKeyError,
  maskSecret,
  optionalEncryptionKey,
  readEncryptionKey,
  requireEncryptionKey,
  secretsMatch,
  UndecryptableSecretError,
} from "./secrets/cipher.js";
export {
  allStoredCredentialNames,
  assertStoredCredentialsAreReadable,
  type CredentialHint,
  credentialRecordName,
  credentialSlotName,
  deleteSourceCredential,
  listCredentialHints,
  putSourceCredential,
  readAllSourceCredentials,
  readSourceCredential,
  rotateEncryptionKey,
  type StoredCredential,
  storedCredentialNames,
} from "./secrets/store.js";
export {
  AmbiguousConnectorError,
  assertSourcesCanBeStored,
  brightDataProvider,
  brightDataProviderId,
  brightDataReddit,
  builtInSources,
  type CandidatePost,
  type ChoiceOptions,
  type ConnectorDefinition,
  type ConnectorDescriptor,
  type ConnectorKey,
  ConnectorNotOfferedError,
  type CredentialCheck,
  type CredentialField,
  clearProviderChoice,
  connectorIdPattern,
  createFakeSource,
  createSourceRegistry,
  createSourceRuntime,
  decideProvider,
  type FakeSource,
  type FakeSourceOptions,
  fakePosts,
  fakeProviderId,
  fakeSourceDefinition,
  fakeSourceId,
  groupByPlatform,
  isOffered,
  type NextPage,
  NoUsableProviderError,
  notOfferedReason,
  offeredConnectors,
  type PlatformConnectors,
  type PlatformDescriptor,
  type PlatformId,
  type ProviderChoices,
  type ProviderDecision,
  type ProviderDescriptor,
  type ProviderId,
  type ProviderReturn,
  platforms,
  providerReturns,
  readProviderChoices,
  reasonsByProvider,
  redditPlatform,
  redditPlatformId,
  type SearchRequest,
  type SearchResult,
  type SocialSource,
  type SourceCredentials,
  type SourceQuery,
  type SourceRegistry,
  type SourceRuntime,
  setProviderChoice,
  UnknownConnectorError,
  UnknownSourceError,
  verdictCount,
  xPlatform,
  xPlatformId,
} from "./sources/index.js";
export {
  type ClassifyOptions,
  createClassifyStep,
  maxClassificationAttempts,
} from "./worker/classify.js";
export { createCollectStep, excerptLength, maxPagesPerPoll } from "./worker/collect.js";
export {
  type CredentialLookup,
  credentialsFromEnvironment,
  credentialsFromStore,
  deprecatedEnvironmentVariableFor,
  environmentVariableFor,
  type MissingCredential,
  missingCredentials,
} from "./worker/credentials.js";
export {
  createEstimateStep,
  type EstimateOptions,
  maxSamplePagesPerProbe,
} from "./worker/estimate.js";
export { createFilterStep, type FilterOptions } from "./worker/filter.js";
export {
  type JobSender,
  jobSenderFor,
  startJobSender,
} from "./worker/jobs.js";
export { createNotifyStep, enqueueNotifications } from "./worker/notify.js";
export {
  allQueues,
  type ClassifyPayload,
  classifyQueue,
  deadLetterQueue,
  type EstimatePayload,
  estimateQueue,
  type FilterPayload,
  filterQueue,
  heartbeatQueue,
  type NotifyPayload,
  notifyQueue,
  type PipelinePayload,
  type PipelineQueue,
  type PollPayload,
  pipelineQueues,
  pollQueue,
  pollQueuePolicy,
  queueDefinitions,
  type RetryPolicy,
  retryPolicy,
  scheduleTickCron,
  scheduleTickQueue,
} from "./worker/queues.js";
export {
  type HeartbeatPayload,
  type StartWorkerOptions,
  startWorker,
  type WorkerHandle,
} from "./worker/runtime.js";
export {
  type DueMonitor,
  enqueueDuePolls,
  findDueMonitors,
  type TickResult,
} from "./worker/schedule.js";
export type {
  PipelineSteps,
  Step,
  StepContext,
  WorkerSteps,
} from "./worker/steps.js";
