export * from "@signalscout/engine";
export { type DraftContext, draftContext } from "./ai/draft-context.js";
export {
  type AiKey,
  aiKeyRecordName,
  type CreateAiKeyInput,
  createAiKey,
  DuplicateAiKeyName,
  deleteAiKey,
  listAiKeys,
  readAiKey,
  readAiKeySecret,
  setDefaultAiKey,
} from "./ai/keys.js";
export {
  classifiedPostCounts,
  type RecordModelCallInput,
  recordModelCall,
} from "./ai/record.js";
export {
  type CreateReplyPromptInput,
  createReplyPrompt,
  DuplicateReplyPromptName,
  deleteReplyPrompt,
  listReplyPrompts,
  type ReplyPrompt,
  seedPresetReplyVoices,
  type UpdateReplyPromptInput,
  updateReplyPrompt,
} from "./ai/reply-prompts.js";
export {
  type AiTaskDraft,
  type AiTaskSettings,
  clearAiTaskSettings,
  previewAiEnvironment,
  readAiEnvironment,
  readAiSettings,
  type SaveAiTaskInput,
  saveAiTaskSettings,
} from "./ai/settings.js";
export {
  type AccountSpend,
  accountSpend,
  type BudgetState,
  budgetState,
  budgetStates,
  checkBudget,
  clearBudget,
  createSpendMeter,
  draftsThisMonth,
  enforceBudget,
  formatMicros,
  getBudget,
  type LastCollection,
  lastCollections,
  type MonitorBudget,
  type MonitorSpend,
  monitorSpend,
  monthStart,
  type PairSpend,
  type RecordSourceUsageInput,
  recordSourceUsage,
  setBudget,
  spendByMonitor,
  spendByPair,
} from "./budget/index.js";
export {
  loadAiEnv,
  loadKeyPolicyEnv,
  loadNotificationEnv,
  loadPipelineEnv,
  loadSignupEnv,
  type NotificationEnv,
  type PipelineEnv,
  parseEnvironment,
  pipelineEnvSchema,
  pipelineFields,
} from "./config/env.js";
export {
  defaultKeyPolicy,
  type KeyPolicy,
  keyPolicies,
  keyPolicyOf,
  machineKeysUsable,
  providerKeyEnvironment,
  sharedInstance,
  webhookSecretEnvironment,
  withoutMachineModelKeys,
} from "./config/machine-keys.js";
export { type SignupMode, signupModes, unclaimedUserId } from "./config/signup.js";
export { createDatabase, type Database } from "./db/client.js";
export {
  applyMigrations,
  type MigrationStream,
  pipelineMigrations,
  runMigrations,
} from "./db/migrate.js";
export {
  type AiTask,
  aiKeys,
  aiSettings,
  aiTasks,
  apiUsage,
  budgets,
  type DiscoveryKind,
  defaultMinimumScore,
  defaultPollIntervalSeconds,
  defaultSimilarityThreshold,
  discoveryKinds,
  type EstimateProbeKind,
  type EstimateStatus,
  type ExhaustedBehaviour,
  embeddingDimensions,
  estimateProbeKinds,
  estimateStatuses,
  exhaustedBehaviours,
  type FilterStage,
  feedback,
  filterDrops,
  filterStages,
  type IntentType,
  intentTypes,
  type ModelCallOutcome,
  type ModelCallPurpose,
  matches,
  maxResumeAttempts,
  minimumPollIntervalSeconds,
  modelCallOutcomes,
  modelCallPurposes,
  modelCalls,
  monitors,
  type PollOutcome,
  type PollRunSource,
  type PollStopReason,
  type Provider,
  pollOutcomes,
  pollStopReasons,
  postDiscoveries,
  posts,
  projects,
  providers,
  queryEstimateProbes,
  queryEstimates,
  replyPrompts,
  type Signal,
  type Source,
  type StageName,
  type StageOutcome,
  type StageRunDetail,
  type StageStopReason,
  signals,
  sourceContinuations,
  sourceCoverage,
  sourceCredentials,
  sourceProviders,
  sources,
  stageNames,
  stageOutcomes,
  stageRuns,
  stageStopReasons,
  type Verdict,
  verdicts,
} from "./db/schema.js";
export {
  daysPerMonth,
  type EstimateProbe,
  type EstimateReport,
  type EstimateRun,
  type EstimateSample,
  type EstimateTotals,
  exceedsCap,
  finishEstimate,
  maxEstimateAttempts,
  type PollShape,
  type ProbeProgress,
  type ProbeReport,
  type ProbeRequest,
  type Projection,
  postsPerDay,
  probesFor,
  projectMonthly,
  readEstimate,
  recordProbeProgress,
  refuseEstimate,
  reportFor,
  type StartEstimateInput,
  sampleExcerptLength,
  samplePostsPerProbe,
  samplesKept,
  sampleWindowDays,
  shortestObservedSpanHours,
  startEstimate,
  totalsFor,
} from "./estimate/index.js";
export {
  currentVerdicts,
  type ExportedVerdict,
  exportFeedback,
  noVerdicts,
  type RecordedVerdict,
  type RecordVerdictInput,
  recordVerdict,
  type VerdictCounts,
  verdictCounts,
} from "./feedback/feedback.js";
export {
  embeddingDropSimilarities,
  type FilterDrop,
  type FilterDropCounts,
  filterDropCounts,
  noFilterDrops,
  recordFilterDrops,
} from "./filter/drops.js";
export {
  type CountNewMatchesOptions,
  countNewMatches,
  csvCell,
  csvFilename,
  cursorPattern,
  defaultPageSize,
  type InboxFilters,
  type InboxMatch,
  type ListMatchesOptions,
  listMatches,
  type MatchCounts,
  type MatchOrder,
  type MatchPage,
  matchCounts,
  matchesToCsv,
  matchOrders,
  matchOwner,
  maximumPageSize,
  noMatchCounts,
  rankDecayPointsPerDay,
  setMatchSaved,
  UnusableCursorError,
  utf8ByteOrderMark,
} from "./matches/index.js";
export {
  allMonitorQueries,
  type CreatedMonitor,
  type CreateMonitorInput,
  canFetchRepliesFor,
  createMonitor,
  deleteMonitor,
  describeMissingCredentials,
  describeSignals,
  getMonitor,
  intentTypeLabel,
  latestPollRuns,
  listMonitors,
  type Monitor,
  type MonitorAnswers,
  type MonitorEnvironment,
  type MonitorFilterSettings,
  type MonitorPlan,
  maxPollRunsRead,
  maxStageRunsRead,
  monitorQueries,
  monitorQueryPlan,
  type PollRun,
  type PollRunRecord,
  pauseMonitor,
  pollRunsKeptPerMonitor,
  type QueryPerformance,
  queryPerformance,
  type ResumeResult,
  readPollRuns,
  readStageRuns,
  recordPollRun,
  recordStageRun,
  redefinesTheMonitor,
  resumeMonitor,
  type SignalDescription,
  type StageRun,
  type StageRunRecord,
  signalDescriptions,
  signalList,
  stageRunsKeptPerMonitor,
  startBlockers,
  type UpdateMonitorInput,
  updateMonitor,
} from "./monitors/index.js";
export {
  assertPublicHost,
  isPublicAddress,
  PrivateAddressError,
  type ResolveHost,
} from "./notifications/address-guard.js";
export {
  type NotificationPass,
  type NotificationTransport,
  processNotifications,
} from "./notifications/deliver.js";
export {
  type EmailShell,
  emailFont,
  emailPalette,
  escapeHtml,
  renderButton,
  renderShell,
  safeUrl,
} from "./notifications/email-theme.js";
export {
  deleteAccountWebhookSecret,
  generateAccountWebhookSecret,
  generateWebhookSecret,
  readWebhookSecretHint,
  type WebhookSecretHint,
  webhookSecretFor,
  webhookSecretRecordName,
} from "./notifications/secret.js";
export {
  defaultNotificationSettings,
  type NotificationInput,
  notificationDefaults,
  notificationInputSchema,
  notificationIssues,
  readNotificationSettings,
  saveNotificationSettings,
} from "./notifications/settings.js";
export { createNotificationTransport, notificationReadiness } from "./notifications/transport.js";
export {
  acceptedTextTypes,
  type DocumentFailure,
  type DocumentResult,
  fetchDocument,
  isPrivateAddress,
  maximumDocumentBytes,
  readUploadedDocument,
} from "./projects/document.js";
export {
  type CreateProjectInput,
  createProject,
  deleteProject,
  getProject,
  listProjects,
  type Project,
  type ProjectAnswers,
  type UpdateProjectInput,
  updateProject,
} from "./projects/projects.js";
export {
  allStoredCredentialNames,
  assertStoredCredentialsAreReadable,
  type CredentialHint,
  credentialRecordName,
  credentialSlotName,
  deleteSourceCredential,
  listCredentialHints,
  putSourceCredential,
  readAllSourceCredentials,
  readSourceCredential,
  rotateEncryptionKey,
  type StoredCredential,
  storedCredentialNames,
} from "./secrets/store.js";
export {
  clearProviderChoice,
  readProviderChoices,
  setProviderChoice,
} from "./sources/choices.js";
export { type ProviderReturn, providerReturns, verdictCount } from "./sources/returns.js";
export {
  type ClassifyOptions,
  createClassifyStep,
  maxClassificationAttempts,
} from "./worker/classify.js";
export { createCollectStep, excerptLength, maxPagesPerPoll } from "./worker/collect.js";
export {
  type CredentialLookup,
  credentialsFromEnvironment,
  credentialsFromStore,
  deprecatedEnvironmentVariableFor,
  environmentVariableFor,
  type MissingCredential,
  missingCredentials,
} from "./worker/credentials.js";
export { admitEveryone, type EntitlementGate } from "./worker/entitlement.js";
export {
  createEstimateStep,
  type EstimateOptions,
  maxSamplePagesPerProbe,
} from "./worker/estimate.js";
export { createFilterStep, type FilterOptions } from "./worker/filter.js";
export {
  type JobSender,
  jobSenderFor,
  startJobSender,
} from "./worker/jobs.js";
export { createNotifyStep, enqueueNotifications } from "./worker/notify.js";
export {
  allQueues,
  type ClassifyPayload,
  classifyQueue,
  deadLetterQueue,
  type EstimatePayload,
  estimateQueue,
  type FilterPayload,
  filterQueue,
  heartbeatQueue,
  type NotifyPayload,
  notifyQueue,
  type PipelinePayload,
  type PipelineQueue,
  type PollPayload,
  pipelineQueues,
  pollQueue,
  pollQueuePolicy,
  queueDefinitions,
  type RetryPolicy,
  retryPolicy,
  scheduleTickCron,
  scheduleTickQueue,
} from "./worker/queues.js";
export {
  type HeartbeatPayload,
  type StartWorkerOptions,
  startWorker,
  type WorkerHandle,
} from "./worker/runtime.js";
export {
  type DueMonitor,
  enqueueDuePolls,
  findDueMonitors,
  type TickResult,
} from "./worker/schedule.js";
export type {
  PipelineSteps,
  Step,
  StepContext,
  WorkerSteps,
} from "./worker/steps.js";
